package jaxws.rpcstyle.wsimportfiles;


import javax.xml.ws.Endpoint;

import jaxws.rpcstyle.ws.RpcImpl;

public class ClientTest {
	public static void main(String[] args) {
		
		Endpoint endpoint = Endpoint.create(new RpcImpl());
		endpoint.publish("http://localhost:9999/ws/hello");
		try {
			RpcImplService helloService = new RpcImplService();
			Rpc hello = helloService.getHelloWorldImplPort();

			System.out.println(hello.getHelloWorldAsString("<RPC Style> with classes generated by wsimport"));

			endpoint.stop();
		} catch (Exception e) {
			e.printStackTrace();
			endpoint.stop();
		}
	}
}
