
package com.linedata.fsb.framework.services.emailsenderservice.test;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2016-10-26T06:51:25.463+02:00
 * Generated source version: 2.6.1
 * 
 */
public final class ClientTest {

    private static final QName SERVICE_NAME = new QName("http://emailsender.shared.services.fimasys.com/", "EmailSenderService");

    private ClientTest() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = new URL("http://localhost:8192/fimasys/framework/fsb-email-sender-service?wsdl");;
        
        EmailSenderService ss = new EmailSenderService(wsdlURL, SERVICE_NAME);
        EmailSenderServicePortType port = ss.getEmailSenderServicePort();  
        
        Email email = new Email();
		email.setRecipient("mao.heng@nokor-group.com");
		email.setSubject("Test");
		
		Body body = new Body();
		body.setBodyType("<![CDATA[HTML]]>");
		body.setTextBody("Testing EmailSender");
		body.setHtmlBody(stripCDATA("<![CDATA[<!DOCTYPE html><html><body><![CDATA[kkkkkkk]]><h1>Testing EmailSender</h1></body></html>]]>"));
		
		email.setBody(body);
		
        {
	        System.out.println("Invoking sendMail...");
	        
	        boolean _sendMail__return = port.sendMail(email);
	        
	        System.out.println("sendMail.result=" + _sendMail__return);

        }

        System.exit(0);
    }


	public static String stripCDATA(String s) {
		if(s == null) {
			return "";
		}
		s = s.trim();
		s = s.replaceAll("<!\\[CDATA", "");
		s = s.replaceAll("]]>", "");
		s = s.replaceAll("\\[", "");
		return s;
	}
}
