package com.linedata.fsb.framework.services.emailsenderservice.test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2016-10-26T06:51:25.560+02:00
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "EmailSenderService", 
                  wsdlLocation = "file:/D:/MHENG/emailsender/EmailSenderService.wsdl",
                  targetNamespace = "http://emailsender.shared.services.fimasys.com/") 
public class EmailSenderService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://emailsender.shared.services.fimasys.com/", "EmailSenderService");
    public final static QName EmailSenderServicePort = new QName("http://emailsender.shared.services.fimasys.com/", "EmailSenderServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/MHENG/emailsender/EmailSenderService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EmailSenderService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/MHENG/emailsender/EmailSenderService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EmailSenderService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EmailSenderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmailSenderService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EmailSenderService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EmailSenderService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EmailSenderService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns EmailSenderServicePortType
     */
    @WebEndpoint(name = "EmailSenderServicePort")
    public EmailSenderServicePortType getEmailSenderServicePort() {
        return super.getPort(EmailSenderServicePort, EmailSenderServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmailSenderServicePortType
     */
    @WebEndpoint(name = "EmailSenderServicePort")
    public EmailSenderServicePortType getEmailSenderServicePort(WebServiceFeature... features) {
        return super.getPort(EmailSenderServicePort, EmailSenderServicePortType.class, features);
    }

}
