
package com.linedata.fsb.framework.services.emailsenderservice.test;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2016-10-26T06:51:25.555+02:00
 * Generated source version: 2.6.1
 * 
 */
 
public class EmailSenderServicePortType_EmailSenderServicePort_Server{

    protected EmailSenderServicePortType_EmailSenderServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new EmailSenderServicePortTypeImpl();
        String address = "http://0.0.0.0:8192/fimasys/framework/fsb-email-sender-service";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new EmailSenderServicePortType_EmailSenderServicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
