package com.linedata.fsb.framework.services.emailsenderservice.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2016-10-26T06:51:25.545+02:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://emailsender.shared.services.fimasys.com/", name = "EmailSenderServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface EmailSenderServicePortType {

    @WebMethod
    @RequestWrapper(localName = "sendMail", targetNamespace = "http://emailsender.shared.services.fimasys.com/", className = "com.linedata.fsb.framework.services.emailsenderservice.test.SendMail")
    @ResponseWrapper(localName = "sendMailResponse", targetNamespace = "http://emailsender.shared.services.fimasys.com/", className = "com.linedata.fsb.framework.services.emailsenderservice.test.SendMailResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean sendMail(
        @WebParam(name = "arg0", targetNamespace = "")
        com.linedata.fsb.framework.services.emailsenderservice.test.Email arg0
    );
}
