
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.linedata.fsb.framework.services.emailsenderservice.test;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2016-10-26T06:51:25.526+02:00
 * Generated source version: 2.6.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "EmailSenderService",
                      portName = "EmailSenderServicePort",
                      targetNamespace = "http://emailsender.shared.services.fimasys.com/",
                      wsdlLocation = "file:/D:/MHENG/emailsender/EmailSenderService.wsdl",
                      endpointInterface = "com.linedata.fsb.framework.services.emailsenderservice.test.EmailSenderServicePortType")
                      
public class EmailSenderServicePortTypeImpl implements EmailSenderServicePortType {

    private static final Logger LOG = Logger.getLogger(EmailSenderServicePortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.linedata.fsb.framework.services.emailsenderservice.test.EmailSenderServicePortType#sendMail(com.linedata.fsb.framework.services.emailsenderservice.test.Email  arg0 )*
     */
    public boolean sendMail(com.linedata.fsb.framework.services.emailsenderservice.test.Email arg0) { 
        LOG.info("Executing operation sendMail");
        System.out.println(arg0);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
