
package jaxws.soaphandler.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ServerInfoService", targetNamespace = "http://ws.soaphandler.jaxws/", wsdlLocation = "http://localhost:8888/ws/server?wsdl")
@HandlerChain(file="handler-chain.xml")
public class ServerInfoService
    extends Service
{

    private final static URL SERVERINFOSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(jaxws.soaphandler.ws.ServerInfoService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = jaxws.soaphandler.ws.ServerInfoService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8888/ws/server?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8888/ws/server?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SERVERINFOSERVICE_WSDL_LOCATION = url;
    }

    public ServerInfoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServerInfoService() {
        super(SERVERINFOSERVICE_WSDL_LOCATION, new QName("http://ws.soaphandler.jaxws/", "ServerInfoService"));
    }

    /**
     * 
     * @return
     *     returns ServerInfo
     */
    @WebEndpoint(name = "ServerInfoPort")
    public ServerInfo1 getServerInfoPort() {
        return super.getPort(new QName("http://ws.soaphandler.jaxws/", "ServerInfoPort"), ServerInfo1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServerInfo
     */
    @WebEndpoint(name = "ServerInfoPort")
    public ServerInfo1 getServerInfoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.soaphandler.jaxws/", "ServerInfoPort"), ServerInfo1.class, features);
    }

}
