
package jaxws.documentstyle.ws.wsimport;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DocumentImplService", targetNamespace = "http://ws.documentstyle.jaxws/", wsdlLocation = "http://localhost:9999/ws/hello?wsdl")
public class DocumentImplService
    extends Service
{

    private final static URL DOCUMENTIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(jaxws.documentstyle.ws.wsimport.DocumentImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = jaxws.documentstyle.ws.wsimport.DocumentImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:9999/ws/hello?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:9999/ws/hello?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DOCUMENTIMPLSERVICE_WSDL_LOCATION = url;
    }

    public DocumentImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocumentImplService() {
        super(DOCUMENTIMPLSERVICE_WSDL_LOCATION, new QName("http://ws.documentstyle.jaxws/", "DocumentImplService"));
    }

    /**
     * 
     * @return
     *     returns Document
     */
    @WebEndpoint(name = "DocumentImplPort")
    public Document getDocumentImplPort() {
        return super.getPort(new QName("http://ws.documentstyle.jaxws/", "DocumentImplPort"), Document.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Document
     */
    @WebEndpoint(name = "DocumentImplPort")
    public Document getDocumentImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.documentstyle.jaxws/", "DocumentImplPort"), Document.class, features);
    }

}
